# AoE2 LLM Arena — Monorepo Commands

set dotenv-load

# Run the gameplay agent
agent *ARGS:
    python -m gameplay_agent {{ARGS}}

# Run the detection server
server *ARGS:
    python -m server {{ARGS}}

# Editable install — agent core only. Uses uv.lock for reproducible resolution.
install:
    uv sync

# Editable install with dev tooling (ruff, pytest, pyright, pre-commit).
install-dev:
    uv sync --extra dev

# Editable install + the detection server extras (fastapi, uvicorn).
install-server:
    uv sync --extra server

# Everything for full local work: agent + server + dev tooling.
install-all:
    uv sync --extra dev --extra server

# Pip-based fallback for environments without uv (e.g. the Windows VM).
# Uses the committed requirements.txt (generated by `uv export`).
install-pip:
    pip install -r requirements.txt
    pip install -e . --no-deps

# Refresh the pip fallback file after changing pyproject.toml. Run after any
# dependency bump alongside `uv lock` (which CI verifies with `uv lock --locked`).
export-requirements:
    uv export --no-hashes --format requirements-txt --no-emit-project --extra dev --extra server > requirements.txt

# Lint with ruff (report only)
lint:
    ruff check .

# Auto-fix lint issues that ruff considers safe
lint-fix:
    ruff check . --fix

# Format with ruff
format:
    ruff format .

# Static type-check with pyright (AI agent code only — see [tool.pyright])
typecheck:
    pyright

# Run tests
test *ARGS:
    pytest {{ARGS}}

# Test coverage report (term-missing format)
coverage:
    pytest --cov --cov-report=term-missing

# Full local quality gate: lint + typecheck + tests
check: lint typecheck test

# Export model to ONNX
export-onnx model="detection/inference/models/aoe2_yolo_v5.pt":
    python -m detection.training.export_onnx --model {{model}}

# Export model to CoreML
export-coreml model="detection/inference/models/aoe2_yolo_v5.pt":
    python -m detection.training.export_coreml --model {{model}}

# Run YOLO training
train model="yolo11n.pt" *ARGS:
    python -m detection.training.train_yolo --model {{model}} {{ARGS}}

# Sync classes.yaml to server bundle
sync-classes:
    cp detection/training/config/classes.yaml server/classes.yaml

# Run scenario evaluations against the executor (~$0.50 for 10 scenarios)
eval *ARGS:
    python -m evaluation.runner {{ARGS}}

# Run all 10 scenarios
eval-all:
    python -m evaluation.runner --all


# ─── Synthetic Arena infrastructure ────────────────────────────────────────
# Stateful services (Langfuse + Postgres + ClickHouse + Redis + MinIO + OTel
# collector) live in docker-compose.yml. Application code stays native.
# See docs/design/synthetic-arena-analysis.md §H for the architectural split.

# Bring the arena stack up in the background (needs `.env` populated)
arena-infra-up:
    docker compose up -d --wait

# Stop containers, preserve volumes (re-up resumes state)
arena-infra-down:
    docker compose down

# Stop AND remove volumes — DATA LOSS, clean slate
arena-infra-nuke:
    docker compose down -v

# Tail logs from every service
arena-infra-logs:
    docker compose logs -f

# Show container + health status
arena-infra-status:
    docker compose ps
    @echo ""
    @echo "Health summary:"
    @docker compose ps --format '{{{{.Service}}}}\t{{{{.Status}}}}' | column -t

# Stack + (later: native arena controller + web UI). Phase 0: just the stack.
arena-up: arena-infra-up

# Race N profiles against each other (real Claude API, requires ANTHROPIC_API_KEY)
arena-race profile="arena/profiles/v1.yaml":
    venv/bin/python -m arena race {{profile}}

# Offline smoke test: mock invoke, no API key, 10 turns per variant
arena-smoke:
    venv/bin/python -m arena smoke

# Bradley-Terry ranking: K rounds x M scenarios x N profiles, with 95% CIs.
# Requires ANTHROPIC_API_KEY. Default config costs ~$1.20 (Haiku, 60 turns x 5 rounds x 4 scenarios x 2 profiles).
arena-rank profile="arena/profiles/ranking-v1.yaml":
    venv/bin/python -m arena rank {{profile}}

# Start the arena replay/inspect web server (FastAPI + SSE).
# Browse to http://localhost:8000/runs to list available event logs.
arena-web-dev port="8000":
    venv/bin/python -m arena.web --port {{port}}

# Install UI dependencies via Bun.
arena-ui-install:
    cd arena/web/ui && bun install

# Run Vite dev server on :5173, proxying /runs, /events, /health to FastAPI on :8000.
# Start `just arena-web-dev` in another shell first.
arena-ui-dev: arena-ui-install
    cd arena/web/ui && bun run dev

# Build the production SPA bundle to arena/web/ui/dist/.
arena-web-build: arena-ui-install
    cd arena/web/ui && bun run build
