"""Per-class confidence thresholds for entity detection.

Single source of truth used by both the detection server (server/app.py)
and the local detector (detection/inference/detector.py).

The CLASS_THRESHOLDS block below is hand-tunable, but is also regenerated by
``detection.inference.sync_thresholds`` from an eval_real_summary.json (the
best-F1 per-class sweep produced by ``evaluate_real.py --conf-sweep``). Keeping
it a plain literal — rather than loading a data file at import — means every
threshold change shows up as a reviewable diff in git.
"""

from __future__ import annotations

DEFAULT_CONFIDENCE: float = 0.35

# Lower thresholds for small or hard-to-detect entities.
# BEGIN GENERATED CLASS_THRESHOLDS  (managed by detection.inference.sync_thresholds)
CLASS_THRESHOLDS: dict[str, float] = {
    "berry_bush": 0.25,
    "deer": 0.20,
    "relic": 0.20,
    "sheep": 0.20,
    "villager": 0.25,
}
# END GENERATED CLASS_THRESHOLDS


def get_threshold(class_name: str) -> float:
    """Return the confidence threshold for a given class name."""
    return CLASS_THRESHOLDS.get(class_name, DEFAULT_CONFIDENCE)
